<?php
return [
    [
        'numero' => '6',
        'campo' => 'cUF',
        'descricao' => 'Código da UF do emitente do Documento Fiscal',
        'observacao' => 'Código da UF do emitente do Documento Fiscal. Utilizar a Tabela do IBGE de código de unidades da federação (Anexo IX - Tabela de UF, Município e País).',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '7',
        'campo' => 'cNF',
        'descricao' => 'Código Numérico que compõe a Chave de Acesso',
        'observacao' => 'Código numérico que compõe a Chave de Acesso. Número aleatório gerado pelo emitente para cada NF-e para evitar acessos indevidos da NF-e (2.0)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '8',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '8',
        'campo' => 'natOp',
        'descricao' => 'Descrição da Natureza da Operação',
        'observacao' => 'Informar a natureza da operação de que decorrer a saída ou a entrada, tais como: venda, compra, transferência, devolução, importação, consignação, remessa (para fins de demonstração, de industrialização ou outra), conforme previsto na alínea i, inciso I, art. 19 do CONVÊNIO S/Nº, de 15 de dezembro de 1970.',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '9',
        'campo' => 'indPag',
        'descricao' => 'Indicador da forma de pagamento',
        'observacao' => '0- Pagamento à vista;1- Pagamento à prazo;2- Outros.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '10',
        'campo' => 'mod',
        'descricao' => 'Código do Modelo do Documento Fiscal',
        'observacao' => '55- NF-e emitida em substituição ao modelo 1 ou 1A:65- NFC-e, utilizada nas operações de venda no varejo (a critério da UF aceitar este modelo de documento).',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '11',
        'campo' => 'serie',
        'descricao' => 'Série do Documento Fiscal',
        'observacao' => 'Série do Documento Fiscal, preencher com zeros na hipótese de a NF-e não possuir série. Série 890-899 de uso exclusivo para emissão de NF-e avulsa, pelo contribuinte com seu certificado digital, através do site do Fisco (procEmi=2). Serie 900-999 – uso exclusivo de NF-e emitidas no SCAN.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1-3',
        'decimal' => '',
        'anotação' => 'Atenção para as séries reservadas.',
    ],
    [
        'numero' => '12',
        'campo' => 'nNF',
        'descricao' => 'Número do Documento Fiscal',
        'observacao' => 'Número do Documento Fiscal',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1-9',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '13',
        'campo' => 'dhEmi',
        'descricao' => 'Data e hora de emissão do Documento Fiscal',
        'observacao' => 'Data e hora no formato UTC (Universal Coordinated Time): AAAA-MM-DDThh:mm:ssTZD',
        'tipo' => 'Data',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => 'Quando informada somente a data e hora, o sistema  o complementará com o Timezone de Origem.',
    ],
    [
        'numero' => '14',
        'campo' => 'dhSaiEnt',
        'descricao' => 'Data e hora de Saída ou da Entrada da Mercadoria/Produto',
        'observacao' => 'Data e hora no formato UTC (Universal Coordinated Time): AAAA-MM-DDThh:mm:ssTZD.Nota: Não informar este campo para a NFC-e.',
        'tipo' => 'Data',
        'ocorrencia' => '0-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => 'Quando informada somente a data e hora, o sistema  o complementará com o Timezone de Origem.',
    ],
    [
        'numero' => '15',
        'campo' => 'tpNF',
        'descricao' => 'Tipo de Operação',
        'observacao' => '0-Entrada;1-Saída;',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '15a',
        'campo' => 'idDest',
        'descricao' => 'Identificador de local de destino da operação',
        'observacao' => '1= Operação interna;2= Operação interestadual;3= Operação com exterior.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '16',
        'campo' => 'cMunFG',
        'descricao' => 'Código do Município de Ocorrência do Fato Gerador',
        'observacao' => 'Informar o município de ocorrência do fato gerador do ICMS. Utilizar tabela do IBGE (Anexo IX - Tabela de UF, Município e País)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '25',
        'campo' => 'tpImp',
        'descricao' => 'Formato de impressão do DANFE',
        'observacao' => '0- Sem geração de DANFE;1- DANFE normal, Retrato;2- DANFE normal, Paisagem;3- DANFE Simplificado;4- DANFE NFC-e;5- DANFE NFC-e em mensagem eletrônica (o envio de mensagem eletrônica pode ser feita de forma simultânea com a impressão do DANFE; usar o tpImp= 5 quando esta for a única forma de disponibilização do DANFE).',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '26',
        'campo' => 'tpEmis',
        'descricao' => 'Forma de Emissão da NF-e',
        'observacao' => '1- Emissão normal (não em contingência);2- Contingência FS-IA com impressão do DANFE em Formulário de Segurança - Impressor Autônomo; 4- EPEC (Evento Prévio de Emissão em Contingência);5- Contingência FS-DA, com impressão do DANFE em Formulário de Segurança - Documento Auxiliar;6- Contingência SVC-AN (SEFAZ Virtual de Contingência do AN);7- Contingência SVC-RS (SEFAZ Virtual de Contingência do RS);9- Contingência off-line da NFC-e;Nota: Para NFC-e somente é válida a opção de contingência: 9-Contingência Offline e, a critério da UF, a opção 4-Contingência EPEC.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '(NT2015.002)',
    ],
    [
        'numero' => '27',
        'campo' => 'cDV',
        'descricao' => 'Dígito Verificador da Chave de Acesso da NF-e',
        'observacao' => 'Informar o DV da Chave de Acesso da NF-e, o DV será calculado com a aplicação do alritmo módulo 11, base 2,9, da Chave de Acesso. (vide item 5 do Manual de Orientação)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '28',
        'campo' => 'tpAmb',
        'descricao' => 'Identificação do Ambiente',
        'observacao' => '1-Produção 2-Homologação',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29',
        'campo' => 'finNfe',
        'descricao' => 'Finalidade de emissão da NF-e',
        'observacao' => '1-NF-e normal2-NF-e complementar3-NF-e de ajuste4-Devolução de mercadoria.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29.1',
        'campo' => 'indFinal',
        'descricao' => 'Indica operação com Consumidor final',
        'observacao' => '0- Não;1- Consumidor final;',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29.2',
        'campo' => 'indPres',
        'descricao' => 'Indicador de presença do comprador no estabelecimento comercal no momento da operação',
        'observacao' => '0- Não se aplica (por exemplo, Nota Fiscal complementar ou de ajuste);1- Operação presencial;2- Operação não presencial, pela internet;3- Operação não presencial, Teleatendimento;4- NFC-e em operação com entrega a domicílio;9- Operação não presencial, outros.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29a',
        'campo' => 'procEmi',
        'descricao' => 'Processo de emissão a NF-e',
        'observacao' => '0-emissão de NF-e com aplicativo do contribuinte1-Emissão de NF-e avulsa pelo Fisco2-emissçao de NF-e avulsa, pelo contribuinte com seu certificado digital, através do site do Fisco3-emissão NF-e pelo contribuinte com aplicativo fornecido pelo Fisco.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29b',
        'campo' => 'verProc',
        'descricao' => 'Versão do Processo de emissão da NF-e',
        'observacao' => 'Informar a versão do aplicativo emissor de NF-e',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-20',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29c',
        'campo' => 'dhCont',
        'descricao' => 'data e hora da entrada em contingência',
        'observacao' => 'Data e hora no formato UTC (Universal Coordinated Time): AAAA-MM-DDThh:mm:ssTZD',
        'tipo' => 'Data',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => 'Nos casos nos quais o Sistema de Origem decidir por contingência esse campo deverá ser informado.',
    ],
    [
        'numero' => '29d',
        'campo' => 'xJust',
        'descricao' => 'Justificativa da entrada em contingencia',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '15-256',
        'decimal' => '',
        'anotação' => 'Nos casos nos quais o Sistema de Origem decidir por contingência esse campo deverá ser informado.',
    ]
];