<?php
return [
    [
        'numero' => '29x.4',
        'campo' => 'cUF',
        'descricao' => 'Código da UF do emitente do Documento Fiscal',
        'observacao' => 'Utilizar tabela do IBGE (Anexo IX - Tabela de UF, Município e País)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.5',
        'campo' => 'AAMM',
        'descricao' => 'Ano e Mês de emissão da NF-e',
        'observacao' => 'AAMM da emissão da NF',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '4',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.6',
        'campo' => 'CNPJ',
        'descricao' => 'CNPJ do emitente',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.7',
        'campo' => 'Mod',
        'descricao' => 'Modelo do Documento Fiscal',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.8',
        'campo' => 'serie',
        'descricao' => 'Série do Documento Fiscal(0para inexistente)',
        'observacao' => 'Informar zero se inexistente',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1-3',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.9',
        'campo' => 'nNF',
        'descricao' => 'Número do Documento Fiscal',
        'observacao' => 'Faixa: 1-999999999',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1-9',
        'decimal' => '',
        'anotação' => '',
    ]
];