<?php
return [
    [
        'numero' => '29x.11',
        'campo' => 'cUF',
        'descricao' => 'Codigo da UF do emitente do Documento Fiscal',
        'observacao' => 'Utilizar tabela do IBGE',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.12',
        'campo' => 'AAMM',
        'descricao' => 'Ano e Mês de emissão da NF-e de produto',
        'observacao' => 'AAMM da emissão da NF de produtor',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '4',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.13',
        'campo' => 'CNPJ',
        'descricao' => 'CNPJ do emitente da NF de prduto',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.14',
        'campo' => 'CPF',
        'descricao' => 'CPF do emitente da NF de produto',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '11',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.15',
        'campo' => 'IE',
        'descricao' => 'IE do emitente da NF de produto',
        'observacao' => '',
        'tipo' => 'caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.16',
        'campo' => 'mod',
        'descricao' => 'Modelo do Documento Fiscal',
        'observacao' => '04 - Produtor Rural 01- NF-e avulsa',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.17',
        'campo' => 'serie',
        'descricao' => 'Série do Documento Fiscal',
        'observacao' => 'Informar zero se não utilizada Série do documento fiscal.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1-3',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '29x.18',
        'campo' => 'nNF',
        'descricao' => 'Número do documento Fiscal',
        'observacao' => 'Faixa: 1-999999999',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1-9',
        'decimal' => '',
        'anotação' => '',
    ]
];