<?php
return [
    [
        'numero' => '51',
        'campo' => 'CNPJ',
        'descricao' => 'CNPJ do emitente',
        'observacao' => 'Informar os zeros não significativos. (NT 2011/004)',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '52',
        'campo' => 'xOrgao',
        'descricao' => 'Órgão Emitente',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '53',
        'campo' => 'matr',
        'descricao' => 'Matrícula do agente',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '54',
        'campo' => 'xAgente',
        'descricao' => 'Nome do agente',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '55',
        'campo' => 'fone',
        'descricao' => 'Telefone',
        'observacao' => 'Preencher com o Código DDD + número do telefone',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '6-14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '56',
        'campo' => 'UF',
        'descricao' => 'Sigla da UF',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '57',
        'campo' => 'nDAR',
        'descricao' => 'Número do Documento de Arrecadação de Receita',
        'observacao' => '(NT 2011/004)',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '58',
        'campo' => 'dEmi',
        'descricao' => 'Data de emissão do Documento de Arrecadação',
        'observacao' => 'Formato "AAAA-MM-DD" (NT 2011/004)',
        'tipo' => 'Data',
        'ocorrencia' => '0-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '59',
        'campo' => 'vDAR',
        'descricao' => 'Valor Total constante no Documento de arrecadação de Receita',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '1-15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '60',
        'campo' => 'repEmi',
        'descricao' => 'Repartição Fiscal emitente',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '61',
        'campo' => 'dPag',
        'descricao' => 'Data de pagamento do Documento de Arrecadação',
        'observacao' => 'Formato "AAAA-MM-DD"',
        'tipo' => 'Data',
        'ocorrencia' => '0-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ]
];