<?php
return [
    [
        'numero' => '65',
        'campo' => 'xNome',
        'descricao' => 'Razão Social ou nome do destinatário',
        'observacao' => 'Tag obrigatória para a NF-e (modelo 55)',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '2-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '77a',
        'campo' => 'indIEDest',
        'descricao' => 'Indicador da IE do Destinatário',
        'observacao' => '1- Contribuinte ICMS (informar a IE do destinatário);2- Contribuinte isento de Inscrição no cadastro de Contribuintes do ICMS;9- Não Contribuinte, que pode ou não possuir Inscrição Estadual no Cadastro de Contribuintes do ICMS. Nota 1: No caso de NFC-e informar indIEDest=9 e não informar a tag IE do destinatário; Nota 2: No caso de operação com o Exterior informar indIEDest=9 e não informar a tag IE do destinatário; Nota 3: No caso de Contribuinte Isento de Inscrição (indIEDest=2), não informar a tag IE do destinatário.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '78',
        'campo' => 'IE',
        'descricao' => 'IE do Destinatário',
        'observacao' => 'Campo opcional. Informar somente os algarismos, sem os caracteres de formatação (ponto, barra hífen, etc.)',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '2-14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '79',
        'campo' => 'ISUF',
        'descricao' => 'Inscrição na SUFRAMA(Obrigatório nas operações sob controle da SUFRAMA)',
        'observacao' => 'Obrigatório, nas operações que se beneficiam de incentivos fiscais existentes nas áreas sob controle da SUFRAMA. A omissão da Inscrição SUFRAMA impede o processamento da operação pelo Sistema de Mercadoria Nacional da SUFRAMA e a liberação da Declaração de Ingresso, prejudicando a comprovação do ingresso/internamento da mercadoria nas áreas sob controle da SUFRAMA.',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '8-9',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '79.1',
        'campo' => 'IM',
        'descricao' => 'Inscrição Municipal do Tomardor do Serviço',
        'observacao' => 'Campo opcional. Pode ser informado na NF-e conjugada, com itens de produtos sujeitos ao ICMS e itens de serviços sujeitos ao ISSQN.',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-15',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '79a',
        'campo' => 'email',
        'descricao' => 'email',
        'observacao' => 'Campo pode ser utilizado para informar o e-mail de recepção da NF-e indicada pelo destinatário.',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ]
];