<?php
return [
    [
        'numero' => '67',
        'campo' => 'xLgr',
        'descricao' => 'Logradouro do Destinatário',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '68',
        'campo' => 'nro',
        'descricao' => 'Número do Destinatário',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '69',
        'campo' => 'xCpl',
        'descricao' => 'Complemento do Destinatário',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '70',
        'campo' => 'xBairro',
        'descricao' => 'Bairro do Destinatário',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '71',
        'campo' => 'cMun',
        'descricao' => 'Código do município do Destinatário',
        'observacao' => 'Utilizar tabela do IBGE ou 9999999 para exterior',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '72',
        'campo' => 'xMun',
        'descricao' => 'Nome do município do Destinatário',
        'observacao' => 'Informar "EXTERIOR" para operações com Exterior',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '73',
        'campo' => 'UF',
        'descricao' => 'Sigla da UF do Destinatário',
        'observacao' => 'Informar "EX" para operações com Exterior',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '74',
        'campo' => 'CEP',
        'descricao' => 'CEP do destinatário',
        'observacao' => 'Informar os zeros não significativos',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '8',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '75',
        'campo' => 'cPais',
        'descricao' => 'Código do País do Destinatário',
        'observacao' => 'Utilizar tabela BACEN1058 - Brasil',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '2-4',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '76',
        'campo' => 'xPais',
        'descricao' => 'Nome do País do Destinatário',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '2-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '77',
        'campo' => 'fone',
        'descricao' => 'Telefone',
        'observacao' => 'Preencher com o Código DDD + número do telefone. Nas operações com o exterior é permitido informar o código do país + código da localidade + número do telefone.',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '6-14',
        'decimal' => '',
        'anotação' => '',
    ]
];