<?php
return [
    [
        'numero' => '91',
        'campo' => 'xLgr',
        'descricao' => 'Logradouro',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '92',
        'campo' => 'nro',
        'descricao' => 'Número',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '93',
        'campo' => 'xCpl',
        'descricao' => 'Complemento',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '94',
        'campo' => 'xBairro',
        'descricao' => 'Bairro',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '95',
        'campo' => 'cMun',
        'descricao' => 'Código do Município',
        'observacao' => 'Utilizar tabela do IBGE (Anexo IX - Tabela de UF, Município e País).',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '96',
        'campo' => 'xMun',
        'descricao' => 'Nome do município',
        'observacao' => 'Informar "EXTERIOR" para operações com Exterior',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '97',
        'campo' => 'UF',
        'descricao' => 'Sigla da UF',
        'observacao' => 'Informar "EX" para operações com Exterior',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ]
];