<?php
return [
    [
        'numero' => '101',
        'campo' => 'cProd',
        'descricao' => 'Código do produto ou serviço',
        'observacao' => 'Preencher com CFOP, caso se trade de item não relacionado com mercadorias/produtos e que o contribuinte não possua codificação própria. Formato “CFOP9999”',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '102',
        'campo' => 'cEAN ',
        'descricao' => 'GTIN(Global Trade Item Number) do produto, antigo código EAN ou código de barras',
        'observacao' => 'Preencher com o código GTIN-8,GTIN-12, GTIN-13 ou GTIN-14, antigos códigos EAN,UPC e DUN-14.). Não Informar caso o produto não tenha o cógido.',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '0,8,12,13,14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '103',
        'campo' => 'xProd',
        'descricao' => 'Descrição do produto ou serviço',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-120',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '104',
        'campo' => 'NCM',
        'descricao' => 'Código NCM com 8 dígitos ou 2 dígitos (genero)',
        'observacao' => 'Código NCM (8 posições), informar o gênero (posição do capítulo do NCM) quando a operação não for de comércio exterior (importação/exportação) ou o produto não seja tributado pelo IPI. Em caso de item de serviço ou item que não tenha produto (Ex. transferência de crédito, crédito do ativo imobilizado, etc.), informar o código 00 (zeros)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2, 8',
        'decimal' => '',
        'anotação' => 'Passou a ser obrigatório. Ou NCM completa, ou Gênero, ou 00 para Item de serviço ou que não tenha produto.',
    ],
    [
        'numero' => '105',
        'campo' => 'EXTIPI',
        'descricao' => 'Código EX da TIPI',
        'observacao' => 'Preencher cde acordo com o código EX da TIPI. Serviço não incluir.',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '2-3',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '107',
        'campo' => 'CFOP',
        'descricao' => 'Código Fiscal de Operações e Prestações(tabela CFOP)',
        'observacao' => 'Utilizar tabela de CFOP',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '4',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '108',
        'campo' => 'uCom',
        'descricao' => 'Unidade Comercial',
        'observacao' => 'Informar a unidade de comercialização do produto.',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-6',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '109',
        'campo' => 'qCom',
        'descricao' => 'Quantidade Comercial',
        'observacao' => 'Informar a quantidade de comercialização do produto.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '0-4',
        'anotação' => '',
    ],
    [
        'numero' => '109a',
        'campo' => 'vUnCom',
        'descricao' => 'Valor Unitário de comercialização',
        'observacao' => 'Informar o valor unitário de comercialização do produto, campo meramente informativo, o Contribuinte pode utilizar a precisão desejada (0-10 decimais). Para efeitos de cálculo, o valor unitário será obtido pela divisão do valor do produto pela quantidade comercial.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '21',
        'decimal' => '0-10',
        'anotação' => '',
    ],
    [
        'numero' => '110',
        'campo' => 'vProd',
        'descricao' => 'Valor Total Bruto dos Produtos ou Serviçoes',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '111',
        'campo' => 'cEANTrib',
        'descricao' => 'GTIN( Global Trade Item Number) da unidade tributável, antigo código EAN ou código de barras',
        'observacao' => 'Preencher com o código GTIN-8, GTIN-12, GTIN-13 ou GTIN-14 (antigos códigos EAN, UPC e DUN-14) da unidade tributável do produto, não informar o conteúdo da TAG em caso de o produto não possuir este código.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '0,8,12,13,14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '112',
        'campo' => 'uTrib',
        'descricao' => 'Unidade tributável',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-6',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '113',
        'campo' => 'qTrib',
        'descricao' => 'Quantidade Tributável',
        'observacao' => 'Informar a quantidade de tributação do produto.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '0-4',
        'anotação' => '',
    ],
    [
        'numero' => '113a',
        'campo' => 'vUnTrib',
        'descricao' => 'Valor Unitário de tributação',
        'observacao' => 'Informar o valor unitário de tributação do produto, campo meramente informativo, o contribuinte pode utilizar a precisão desejada (0-10 decimais). Para efeitos de cálculo, o valor unitário será obtido pela divisão do valor do produto pela quantidade tributável.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '21',
        'decimal' => '0-10',
        'anotação' => '',
    ],
    [
        'numero' => '114',
        'campo' => 'vFrete',
        'descricao' => 'Valor total do frete',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '115',
        'campo' => 'vSeg',
        'descricao' => 'Valor total do Seguro',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '116',
        'campo' => 'vDesc',
        'descricao' => 'Valor do desconto',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '116a',
        'campo' => 'vOutro',
        'descricao' => 'outras Despesas acessórias',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '116b',
        'campo' => 'indTot',
        'descricao' => 'Indica se valor do item (cProd) entra no valor total da NF-e (vProd)',
        'observacao' => 'Este campo deverá ser preenchido com:0- Valor do item (vProd) não compõe o valor total da NF-e. 1- Valor do item (vProd) compõe o valor total da NF-e (vProd)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '128m',
        'campo' => 'xPed',
        'descricao' => 'Numero do pedido de compra',
        'observacao' => 'Informação de interesse do emissor para controle do B2B.',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-15',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '128n',
        'campo' => 'nItemPed',
        'descricao' => 'Item do pedido de compra',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '6',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '128p',
        'campo' => 'nFCI',
        'descricao' => 'Número de controle da FCI - Ficha de Conteúdo de Importação',
        'observacao' => '(NT 2013.006)',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '36',
        'decimal' => '',
        'anotação' => 'Informação relacionada com a Resolução 13/2012 do Senado Federal. Formato: Algarismo, letras maiúsculas de "A" a "F" e o caractere hífen.Exemplo:B01F70AF-10BF-4B1F-848C-65FF57F616FE',
    ]
];