<?php
return [
    [
        'numero' => '118',
        'campo' => 'nDi',
        'descricao' => 'Número do Documento de Importação DI/DSI/DA/DREI/etc.',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-12',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '119',
        'campo' => 'dDi',
        'descricao' => 'Data de Registro da DI/DSI/DA/DREI/etc.',
        'observacao' => 'AAAA-MM-DD',
        'tipo' => 'Data',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '120',
        'campo' => 'xLocDesemb',
        'descricao' => 'Local de desembaraço',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '121',
        'campo' => 'UFDesemb',
        'descricao' => '',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '122',
        'campo' => 'dDesemb',
        'descricao' => 'Data do Desembaraço Aduaneiro',
        'observacao' => 'AAAA-MM-DD',
        'tipo' => 'Data',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '122a',
        'campo' => 'tpViaTransp',
        'descricao' => 'Via de transporte internacional informada na Declaração de Importação (DI)',
        'observacao' => '1-   Marítma;2-   Fluvial;3-   Lacustre;4-   Aéreo;5-   Postal;6-   Ferroviária;7-   Rodoviária;8-   Conduto / Rede Transmissão;9-   Meios Próprios;10- Entrada / Saída ficta.11- Courier;12- Handcarry. (NT 2013/005 v1.10).',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '122b',
        'campo' => 'vAFRMM',
        'descricao' => 'Valor da AFRMM - Adicional ao Frete para Renovação da Marinha Mercante',
        'observacao' => 'A tag deve ser informada no caso da via de transporte marítma',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '122c',
        'campo' => 'tpIntermedio',
        'descricao' => 'Forma de importação quanto a intermediação',
        'observacao' => '1- Importação por conta própria;2- Importação por conta e ordem;3- Importação por encomenda;',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '122d',
        'campo' => 'CNPJ',
        'descricao' => 'CNPJ do adquirente ou do encomendante',
        'observacao' => 'Obrigatória a informação no caso de importação por conta e ordem ou por encomenda. Informar os zeros não significativos',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '122e',
        'campo' => 'UFTerceiro',
        'descricao' => 'Sigla da UF do adquirente ou do encomendante',
        'observacao' => 'Obrigatória a informação no caso de importação por conta e ordem ou por encomenda. Não aceita o valor "EX".',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '123',
        'campo' => 'cExportador',
        'descricao' => 'Código do exportador',
        'observacao' => 'Código do exportador, usado nos sistemas internos de informação do emitente da NF-e',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ]
];