<?php
return [
    [
        'numero' => '125',
        'campo' => 'nAdicao',
        'descricao' => 'Número da adição',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1-3',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '126',
        'campo' => 'nSeqAdic',
        'descricao' => 'Número sequëncial do item',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1-3',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '127',
        'campo' => 'cFabricante',
        'descricao' => 'Código do fabricante estrangeiro',
        'observacao' => 'Código do fabricante estrangeiro, usado nos sistemas internos de informação do emitente da NF-e',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '128',
        'campo' => 'vDescDi',
        'descricao' => 'Valor do desconto do item da DI-adição',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '128.1',
        'campo' => 'nDraw',
        'descricao' => 'Número do ato concessório de Drawback',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '0, 9 ou 11',
        'decimal' => '',
        'anotação' => 'O número do Ato Concessório de Suspensão deve ser preenchido com 11 dígitos (AAANNNNNND) e o númerodo Ato Concessório de Drawback Isenção deve ser preenchido com 9 dígitos (AANNNNNND). (Observação incluída na NT 2013/005 v. 1.10)',
    ]
];