<?php
return [
    [
        'numero' => '153',
        'campo' => 'nLote',
        'descricao' => 'Número do Lote do medicamento e de matérias-primas farmacêuticas',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '1-20',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '154',
        'campo' => 'qLote',
        'descricao' => 'Quantidade de produto no lote do medicamento e de matérias-primas farmacêuticas',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '11',
        'decimal' => '3',
        'anotação' => '',
    ],
    [
        'numero' => '155',
        'campo' => 'dFab',
        'descricao' => 'Data de fabricação',
        'observacao' => '“AAAA-MM-DD”',
        'tipo' => 'Data',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '156',
        'campo' => 'dVal',
        'descricao' => 'Data de Validade',
        'observacao' => '“AAAA-MM-DD”',
        'tipo' => 'Data',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '157',
        'campo' => 'Vpmc',
        'descricao' => 'Preço máximo consumidor',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ]
];