<?php
return [
    [
        'numero' => '186',
        'campo' => 'orig',
        'descricao' => 'Origem da mercadoria',
        'observacao' => '(NT 2013.006)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => 'Origem da mercadoria:0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8;1 - Estrangeira - Importação direta, exceto a indicada no código 6;2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7;3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% e inferior ou igual a 70%;4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes;5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%;6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural;7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista da CAMEX e gás natural.8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%;',
    ],
    [
        'numero' => '187',
        'campo' => 'CST',
        'descricao' => 'Tributação do ICMS',
        'observacao' => '20-Com redução de base de cálculo',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '188',
        'campo' => 'modBC',
        'descricao' => 'Modalidade de determinação da BC do ICMS',
        'observacao' => '(0-Margem Valor Agragado(%);1-Pauta(valor);2-Preço tabelado Máx.(valor);3-valor da operação',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '189',
        'campo' => 'pRedBC',
        'descricao' => 'Percentual da Redução de BC',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '190',
        'campo' => 'vBC',
        'descricao' => 'Valor da BC do ICMS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '191',
        'campo' => 'pICMS',
        'descricao' => 'Alíquota do imposto',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '192',
        'campo' => 'vICMS',
        'descricao' => 'Valor do ICMS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '192.2',
        'campo' => 'vICMSDeson',
        'descricao' => 'Valor do ICMS desonerado',
        'observacao' => 'Informar apenas nos motivos de desoneração documentados abaixo.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '192.3',
        'campo' => 'motDesICMS',
        'descricao' => 'Motivo da desoneração do ICMS',
        'observacao' => 'Campo será preenchido quando o campo anterior estiver preenchido. Infomar o motivo da desoneração:3- Uso na agricultura;9- Outros;12- Órgão de fomento e desenolvimento agropercuário.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ]
];