<?php
return [
    [
        'numero' => '194',
        'campo' => 'orig',
        'descricao' => 'Origem da mercadoria',
        'observacao' => '(NT 2013.006)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => 'Origem da mercadoria:0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8;1 - Estrangeira - Importação direta, exceto a indicada no código 6;2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7;3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% e inferior ou igual a 70%;4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes;5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%;6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural;7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista da CAMEX e gás natural.8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%;',
    ],
    [
        'numero' => '195',
        'campo' => 'CST',
        'descricao' => 'Tributação do ICMS',
        'observacao' => '30 – Isenta ou não tributada e com cobrança do ICMS por substituição tributária.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '196',
        'campo' => 'modBCST',
        'descricao' => 'Modalidade de determinação da BC do ICMS ST',
        'observacao' => '0-Preço tabelado ou máximo sugerido;1-Lista Negativa(valor);2-Lista Positiva(valor);3-Lista Neutra,(valor);4-Margem Valor Agregado(%);5-Pauta,(valor)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '197',
        'campo' => 'pMVAST',
        'descricao' => 'Percentual da margem de valor Adicionado do ICMS ST',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '198',
        'campo' => 'pRedBCST',
        'descricao' => 'Percentual da Redução de BC do ICMS ST',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '199',
        'campo' => 'vBCST',
        'descricao' => 'Valor da BC do ICMS ST',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '200',
        'campo' => 'pICMSST',
        'descricao' => 'Alíquota do imposto do ICMS ST',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '201',
        'campo' => 'vICMSST',
        'descricao' => 'Valor do ICMS ST(Valor do ICMS ST retido)',
        'observacao' => 'Valor do ICMS ST retodp',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '201.2',
        'campo' => 'vICMSDeson',
        'descricao' => 'Valor do ICMS desonerado',
        'observacao' => 'Informar apenas nos motivos de desoneração documentados abaixo.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '201.3',
        'campo' => 'motDesICMS',
        'descricao' => 'Motivo da desoneração do ICMS',
        'observacao' => 'Campo será preenchido quando o campo anterior estiver preenchido. Infomar o motivo da desoneração:6- Utilitários e Motocicletas da Amazônia Ocidental e Áreas de Livre Comércio (Resolução 714/88 e 790/94 - CONTRAN e suas alterações);7- SUFRAMA;9- Outros.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ]
];