<?php
return [
    [
        'numero' => '245.02',
        'campo' => 'orig',
        'descricao' => 'Origem da mercadoria',
        'observacao' => '(NT 2013.006)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => 'Origem da mercadoria:0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8;1 - Estrangeira - Importação direta, exceto a indicada no código 6;2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7;3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% e inferior ou igual a 70%;4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes;5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%;6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural;7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista da CAMEX e gás natural.8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%;',
    ],
    [
        'numero' => '245.03',
        'campo' => 'CST',
        'descricao' => 'tributação do ICMS',
        'observacao' => '10 - Tributada e com cobrança do ICMS por substituição tributária; 90 – Outros.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '245.04',
        'campo' => 'modBC',
        'descricao' => 'modalidade de determinação da BC do ICMS ST',
        'observacao' => '0 - Margem Valor Agregado (%); 1 - Pauta (Valor); 2 - Preço Tabelado Máx. (valor);3 - valor da operação.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '245.05',
        'campo' => 'vBC',
        'descricao' => 'valor do bc do ICMS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '245.06',
        'campo' => 'pRedBC',
        'descricao' => 'Percentual da Redução de BC',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '245.07',
        'campo' => 'pICMS',
        'descricao' => 'aliquota do imposto',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '245.08',
        'campo' => 'vICMS',
        'descricao' => 'valor do iCMS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '245.09',
        'campo' => 'modBCST',
        'descricao' => 'modalidade de determinação da BC do ICMS ST',
        'observacao' => '0 – Preço tabelado ou máximo sugerido; 1 - Lista Negativa (valor); 2 - Lista Positiva (valor);3 - Lista Neutra (valor);4 - Margem Valor Agregado (%); 5 - Pauta (valor);',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '245.10',
        'campo' => 'pMVAST',
        'descricao' => 'percentual da margem de valor Adicionado do ICMS ST',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '245.11',
        'campo' => 'pRedBCST',
        'descricao' => 'percentual da redução de bc do ICMS ST',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '245.12',
        'campo' => 'vBCST',
        'descricao' => 'valor da bc do ICMS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '245.13',
        'campo' => 'pICMSST',
        'descricao' => 'aliquota do imposto do ICMS ST',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '245.14',
        'campo' => 'vICMSST',
        'descricao' => 'valor do ICMS ST',
        'observacao' => 'Valor do ICMS ST',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '245.15',
        'campo' => 'pBCOp',
        'descricao' => 'Percentual da BC operação própria',
        'observacao' => 'Percentual para determinação do valor da Base de Cálculo da operação própria.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '245.16',
        'campo' => 'UFST',
        'descricao' => 'UF para qual é devido o ICMS',
        'observacao' => 'Sigla da UF para qual é devido o ICMS ST da operação.Informar "EX" para Exterior. ',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ]
];