<?php
return [
    [
        'numero' => '245.18',
        'campo' => 'orig',
        'descricao' => 'origem da mercadoria',
        'observacao' => '(NT 2013.006)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1',
        'decimal' => '',
        'anotação' => 'Origem da mercadoria:0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8;1 - Estrangeira - Importação direta, exceto a indicada no código 6;2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7;3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% e inferior ou igual a 70%;4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes;5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%;6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural;7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista da CAMEX e gás natural.8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%;',
    ],
    [
        'numero' => '245.19',
        'campo' => 'CST',
        'descricao' => 'tributação do ICMS',
        'observacao' => '41 – Não Tributado',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '245.20',
        'campo' => 'vBCSTRet',
        'descricao' => 'valor do bc do ICMS ST retido na UF remetente',
        'observacao' => 'Informar o valor da BC do ICMS ST retido na UF remetente',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '245.21',
        'campo' => 'vICMSSTRet',
        'descricao' => 'valor do icms st retido na UF rementente',
        'observacao' => 'Informar o valor do ICMS ST retido na UF remetente',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '245.22',
        'campo' => 'vBCSTDest',
        'descricao' => 'Valor do BC do ICMS ST da UF destino',
        'observacao' => 'Informar o valor da BC do ICMS ST da UF destino',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '245.23',
        'campo' => 'vICMSSTDest',
        'descricao' => 'valor do ICMS ST da UF destino',
        'observacao' => 'Informar o valor da BC do ICMS ST da UF destino',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ]
];