<?php
return [
    [
        'numero' => '',
        'campo' => '',
        'descricao' => '',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '',
        'campo' => '',
        'descricao' => '',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '',
        'campo' => '',
        'descricao' => '',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '',
        'campo' => '',
        'descricao' => '',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '',
        'campo' => '',
        'descricao' => '',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '',
        'campo' => '',
        'descricao' => '',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '',
        'campo' => '',
        'descricao' => '',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '',
        'campo' => '',
        'descricao' => '',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '',
        'decimal' => '',
        'anotação' => '',
    ]
];