<?php
return [
    [
        'numero' => '247',
        'campo' => 'cIEnq',
        'descricao' => 'Classe de enquadramento do IPI para Cigarros e Bebidas',
        'observacao' => 'Preenchimento conforme AtosNormativos editados pela Receita Federal (Observação 2)',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-5',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '248',
        'campo' => 'CNPJProd',
        'descricao' => 'CNPJ do produtor da mercadoria, quando diferente do emitente. Somente para os casos de exportação direta ou indireta',
        'observacao' => 'Informar os zeros não significativos',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '249',
        'campo' => 'cSelo',
        'descricao' => 'Código do selo de controle IPI',
        'observacao' => 'Preenchimento conforme Atos Normativos editados pela Receita Federal (Observação 3)',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '250',
        'campo' => 'qSelo',
        'descricao' => 'Quantidade de selo de controle',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '1-12',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '251',
        'campo' => 'cEnq',
        'descricao' => 'Código de Enquadramento Legal do IPI ',
        'observacao' => 'Condificação conforme "Código de Enquadramento legal do IPI" - Anexo XIV da NT2015.002',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '1-3',
        'decimal' => '',
        'anotação' => '(NT2015.002)',
    ]
];