<?php
return [
    [
        'numero' => '328',
        'campo' => 'vBC',
        'descricao' => 'Base de cálculos do ICMS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '329',
        'campo' => 'vICMS',
        'descricao' => 'Valor total do ICMS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '329.01',
        'campo' => 'vICMSDeson',
        'descricao' => 'Valor Total do ICMS desonerado',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '330',
        'campo' => 'vBCST',
        'descricao' => 'Base de Cálculo do ICMS ST',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '331',
        'campo' => 'vST',
        'descricao' => 'Valot Total do ICMS ST',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '332',
        'campo' => 'vProd',
        'descricao' => 'Valor Total dos produtos e serviços',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '333',
        'campo' => 'vFrete',
        'descricao' => 'Valor total do frete',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '334',
        'campo' => 'vSeg',
        'descricao' => 'Valor total do Seguro',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '335',
        'campo' => 'vDesc',
        'descricao' => 'Valor Total do Desconto',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '336',
        'campo' => 'vII',
        'descricao' => 'Valot Total do II',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '337',
        'campo' => 'vIPI',
        'descricao' => 'Valor Total do IPI',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '338',
        'campo' => 'vPIS',
        'descricao' => 'Valor Total do PIS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '339',
        'campo' => 'vCOFINS',
        'descricao' => 'Valor totald do COFINS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '340',
        'campo' => 'vOutro',
        'descricao' => 'Outras Despesas acessórias',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '341',
        'campo' => 'vNF',
        'descricao' => 'Valor Total da NF-e',
        'observacao' => 'Vide validação para este campo na regraa de validação "W16-xx".',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '341a',
        'campo' => 'vTotTrib',
        'descricao' => 'Valor aproximado total de tributos federais, estaduais e municipais',
        'observacao' => '(NT 2013.003)',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ]
];