<?php
return [
    [
        'numero' => '349',
        'campo' => 'vRetPIS',
        'descricao' => 'Valor Retido de PIS',
        'observacao' => 'Exemplos de atos normativos que definem obrigatoriedade da retenção de contribuições: a) IRPJ/CSLL/PIS/COFINS - Fonte - Recebimentos de Órgãos Públicos Federais Lei nº 9.430, de 27 de dezembro de 1996, art. 64 Lei nº 10.833/2003, art. 34 como normas infralegais, temos como exemplo: Instrução Normativa SRF nº 480/2004 e Instrução Normativa nº 539, de 25/04/2005.  b) Retenção do Imposto de Renda pelas Fontes Pagadoras REMUNERAÇÃO DE SERVIÇOS PROFISSIONAIS PRESTADOS POR PESSOA JURÍDICA LEI Nº 7.450/85, ART. 52  c) IRPJ, CSLL, COFINS e PIS - Serviços Prestados por Pessoas Jurídicas - Retenção na Fonte Lei nº 10.833 de 29.12.2003, arts. 30, 31, 32, 35 e 36',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '350',
        'campo' => 'vRetCOFINS',
        'descricao' => 'Valor Retido de COFINS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '351',
        'campo' => 'vRetCSLL',
        'descricao' => 'Valor Retido de CSLL',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '352',
        'campo' => 'vBCIRRF',
        'descricao' => 'Base de Cálculo do IRRF',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '353',
        'campo' => 'vIRRF',
        'descricao' => 'Valor Retido do IRRF',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '354',
        'campo' => 'vBCRetPrev',
        'descricao' => 'Base de Cálculo da Retenção da Previdência Social',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '355',
        'campo' => 'vRetPrev',
        'descricao' => 'Valor da Retenção da Previdência Social',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ]
];