<?php
return [
    [
        'numero' => '361',
        'campo' => 'xNome',
        'descricao' => 'Razão Social ou nome',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '2-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '362',
        'campo' => 'IE',
        'descricao' => 'Inscrição Estadual',
        'observacao' => 'Informar: - Inscrição Estadual do transportador contribuinte do ICMS, sem caracteres de formatação (ponto, barra, hífen, etc.); - Literal "ISENTO" para transportador isento de inscrição no cadastro de contribuintes ICMS; - Não informar a tag para não contribuinte do ICMS. A UF deve ser informada se informado uma IE.',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '0-14',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '363',
        'campo' => 'xEnder',
        'descricao' => 'Endereço Completo',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '364',
        'campo' => 'xMun',
        'descricao' => 'Nome do Município',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '365',
        'campo' => 'UF',
        'descricao' => 'Sigla da UF',
        'observacao' => 'A UF deve ser informada se informado uma IE. Informar "EX" para Exterior.',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '2',
        'decimal' => '',
        'anotação' => '',
    ]
];