<?php
return [
    [
        'numero' => '367',
        'campo' => 'vServ',
        'descricao' => 'Valor do Serviço',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '368',
        'campo' => 'vBCRet',
        'descricao' => 'BC da Retenção do ICMS',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '369',
        'campo' => 'pICMSRet',
        'descricao' => 'Alíquota da Retenção',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '2-4',
        'anotação' => '',
    ],
    [
        'numero' => '370',
        'campo' => 'vICMSRet',
        'descricao' => 'Valor do ICMS Retido',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '371',
        'campo' => 'CFOP',
        'descricao' => 'CFOP(tabela CFOP)',
        'observacao' => 'Utilizar Tabela de CFOP.',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '4',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '372',
        'campo' => 'cMunFG',
        'descricao' => 'Código do município de ocorrência do fato gerador do ICMS do transporte(IBGE)',
        'observacao' => 'Informar o município de ocorrência do fato gerador do ICMS do transporte. Utilizar a Tabela do IBGE (Anexo VII - Tabela de UF, Município e País)',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '',
        'anotação' => '',
    ]
];