<?php
return [
    [
        'numero' => '382',
        'campo' => 'qVol',
        'descricao' => 'Quantidade de Volume',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '1-15',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '383',
        'campo' => 'esp',
        'descricao' => 'Espécie dos volumes transportados',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '384',
        'campo' => 'marca',
        'descricao' => 'Marca dos volumes transportados',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '385',
        'campo' => 'nVol',
        'descricao' => 'Numeração dos volumes transportados',
        'observacao' => '',
        'tipo' => 'Caractere',
        'ocorrencia' => '0-1',
        'tamanho' => '1-60',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '386',
        'campo' => 'pesoL',
        'descricao' => 'Peso Líquido(em Kg)',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '3',
        'anotação' => '',
    ],
    [
        'numero' => '387',
        'campo' => 'pesoB',
        'descricao' => 'Peso Bruto(em Kg)',
        'observacao' => '',
        'tipo' => 'Numérico',
        'ocorrencia' => '0-1',
        'tamanho' => '15',
        'decimal' => '3',
        'anotação' => '',
    ]
];