<?php
return [
    [
        'numero' => '410',
        'campo' => 'safra',
        'descricao' => 'Identificação da safra',
        'observacao' => 'Informar a safra, AAAA ou AAAA/AAAA. v2.0',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '4-9',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '411',
        'campo' => 'ref',
        'descricao' => 'Mes e ano  de referencia',
        'observacao' => 'Informar o mês e ano de referência, MM/AAAA. v2.0',
        'tipo' => 'Caractere',
        'ocorrencia' => '1-1',
        'tamanho' => '7',
        'decimal' => '',
        'anotação' => '',
    ],
    [
        'numero' => '415',
        'campo' => 'qTotMes',
        'descricao' => 'Quantidade total do mes',
        'observacao' => 'v2.0',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '21',
        'decimal' => '10',
        'anotação' => '',
    ],
    [
        'numero' => '416',
        'campo' => 'qTotAnt',
        'descricao' => 'Quantidade total anterior',
        'observacao' => 'v2.0',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '21',
        'decimal' => '10',
        'anotação' => '',
    ],
    [
        'numero' => '417',
        'campo' => 'qTotGer',
        'descricao' => 'Quantidade total geral',
        'observacao' => 'v2.0',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '21',
        'decimal' => '10',
        'anotação' => '',
    ],
    [
        'numero' => '421',
        'campo' => 'vFor',
        'descricao' => 'Valor dos fornecimentos',
        'observacao' => 'Valor dos Fornecimentos v2.0',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '422',
        'campo' => 'vTotDed',
        'descricao' => 'valor total da dedução',
        'observacao' => 'Valor das deduções v2.0',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ],
    [
        'numero' => '423',
        'campo' => 'vLiqFor',
        'descricao' => 'Valor liquido dos fornecimentos',
        'observacao' => 'Valor Líquido dos Fornecimentos v2.0',
        'tipo' => 'Numérico',
        'ocorrencia' => '1-1',
        'tamanho' => '15',
        'decimal' => '2',
        'anotação' => '',
    ]
];